services:
  ppl_site:
    container_name: ppl_site
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - nginx
    command: npm run start
    restart: unless-stopped

networks:
  nginx:
    external: true
    name: nginx
