name: Pull Request Checks

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    test-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cache Node.js modules
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.npm
                      .next/cache
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run build
              run: npm run build
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cache Node.js modules
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.npm
                      .next/cache
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm i

            - name: Eslint check
              run: npm run lint
